# Generated by Django 2.2 on 2020-05-08 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stripe_app.User')),
            ],
            options={
                'verbose_name': 'Premium Product',
                'verbose_name_plural': 'Premium Products',
            },
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
